### ISSUE TITLE
我在尝试将来自QQ-MHT文件和WeChat数据展示时，前台不显示任何数据

### ISSUE THREAD

**Issue by Coooolfan** [lqzhgood/Shmily-Show#1]
我已经完成了[项目Shmily-Get-QQ-PC_MHT](https://github.com/lqzhgood/Shmily-Get-QQ-PC_MHT)和[项目Shmily-Get-Wechat](https://github.com/lqzhgood/Shmily-Get-Wechat)的导出操作。
其中WeChat的导出我参考了[您在此提出的解决方案](https://github.com/lqzhgood/Shmily-Get-Wechat/issues/2)，通过指定对方的Wxid来减少数据量成功导出。

现在我遇到了这些问题：

1. 在尝试运行此项目时，我不太能理解Readme文件中数据文件和资源文件的放置方式。下图是三个项目的相关文件的列表
<img width="816" alt="image" src="https://github.com/lqzhgood/Shmily-Show/assets/78391548/667c69bf-f65d-483e-8a67-236191324b5f">
<img width="816" alt="image" src="https://github.com/lqzhgood/Shmily-Show/assets/78391548/5af466ed-5389-496d-9166-c137bff45420">
<img width="816" alt="image" src="https://github.com/lqzhgood/Shmily-Show/assets/78391548/3b924ae4-5884-42aa-b5a9-6e00d0c2a187">

2. 当我以此文件结构运行`npm run build`时，我遇到了大量的错误。其中大多为`sourceCount.js`中变量`sourceData`的相关错误，排查中发现此变量实际为空值，导致对其成员变量的操作失败。

3. 在尝试注释与此相关的代码后（没细看代码，我猜这是与统计相关的代码，删除应该不影响聊天内容的展示） ，项目编译通过，按照Readme中提示的文件操作后，打开浏览器内容全空。
<img width="1280" alt="image" src="https://github.com/lqzhgood/Shmily-Show/assets/78391548/5bb4e840-16eb-4314-9ef6-6c8bd67d0166">

此外，在查看WeChat导出的结果`db-android_msg_res.json`时，我发现其中仅有对方发送的内容，没有看到我发送的内容。不知是否与java程序的导出操作有关。另，在文件`Shmily-Get-Wechat\export\db-android\2 dbToJson\config.js`中的`FILTER_USER`参数，我正确地填写了对方的Wxid。

不得不说，这是一个艰巨的大工程，爱来自中国

**Comment by lqzhgood** [comment]
这是因为`[数据文件]` 放错位置了，所以统计报错，显示数据为空。

`[数据文件]` 需要放到 `memoryweb\src\assets\data\msg`下

 我更新一下文档。

**Comment by lqzhgood** [comment]
我细化了文档， 你参考以下文档看能理解不?

http://lqzhgood.github.io/Shmily/guide/use/get.html#_4-获取数据
https://github.com/lqzhgood/Shmily-Show#使用


```
- memoryweb
  - src
    - assets 
      - data
        - msg  <--- [数据文件] 夹
          - MobileQQ-lqzh-20201212.json
          - MobileQQ-lqzh-20230101.json
          - Wechat-lqzh-20230203.json
          ...

- msgData
  - data  <--- [资源文件] 夹
    - MobileQQ-lqzh-20201212
        - images
        - videos
        ...
    - MobileQQ-lqzh-20230101
        - images
        - videos
        ...
    - Wechat-lqzh-20230203
        - images
        - videos
        ...
```


############

Get 项目还有以下问题

- 现有的 `Get` 输出的 `dist` 目录有很多 `.json` 只是中间数据，产生了误导。后续我会把他们都放到 `dist\_temp` 中
- `[数据文件]` 名称太随意了，后续会把命名规范
- `[资源文件]` 夹名称取 `[数据文件]` 名
