### ISSUE TITLE
能否支持其它工具导出的微信数据？

### ISSUE THREAD

**Issue by fengyu397** [lqzhgood/Shmily-Show#4]
请问能否支持其它工具导出的数据，如 https://github.com/LC044/WeChatMsg
在此基础上进行数据分析与统计呢？

**Comment by lqzhgood** [comment]
我的 [理念](http://lqzhgood.github.io/Shmily/guide/concept.html) 就是少造轮子~ 
所以 Shmily 是拆分且非黑盒的~ 

也就是支持其他数据复用 Show (查询搜索 分析统计).
前提是导出为我约定的格式~[Shimly-Msg](http://lqzhgood.github.io/Shmily/guide/use/msg/schema.html)
